---
- name: Parcha un conjunto de servidores linux
  #Ejecutar con privilegios elevados
  become: yes
  hosts: all
  tasks:
    - name: Ejecuta comando para actualizar paquetes
      ansible.builtin.dnf:
        name: "*"
        state: latest
