---
- name: Parcha un conjunto de servidores linux
  become: yes
  # A quienes se les va a operar
  #all, servidores dentro de un inventario o grupo
  hosts: all
  tasks:
    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
