---
- name: Parcha un conjunto de servidores linux
  become: yes
  # A quienes se les va a operar
  #all, servidores dentro de un inventario o grupo
  hosts: node1,node2
  tasks:
    - name: Ejecuta comando para actualizar paquetes
      ansible.builtin.dnf:
        name: "*"
        state: latest
